feat: Update http3 lib, Bump version
XDeFi-tech/xchainpy-lib pull request #2
Opened 2024-05-30 11:08 UTC by Sotatek-BinhDo

## Context
- Investigate xchainpy-thorchain

## Change
- Update the version for the http3 lib
- Bump the version

## Ticket:
[package dependency and rebuild/update dependencies](https://xdefi-tech.atlassian.net/browse/XDEFI-7806)

2024-05-30 11:13 UTC, DJercic requested changes
we have to fix the version

2024-05-30 12:00 UTC, Sotatek-BinhDo commented on xchainpy/xchainpy_client/requirements.txt
> +http3
updated
ref here: 8a02bddc28aa160ad2cb75954805927bb42fcc1c

2024-05-31 11:52 UTC, 0xnabil commented
Some dependencies need to be bumped too in order to avoid conflicts at routing project level:
- ecdsa==0.17.0
- requests==2.29.0

2024-06-03 04:21 UTC, Sotatek-BinhDo commented
> Some dependencies need to be bumped too in order to avoid conflicts at routing project level:
> 
>     * ecdsa==0.17.0
> 
>     * requests==2.29.0

updated
ref here: cea59758e4150d4b749f8b2bfc86cb48808cf7ec

2024-06-03 07:23 UTC, 0xnabil approved these changes

2024-06-04 07:32 UTC, merged